### ISSUE TITLE
mdx output should use omd instead of pandoc

### ISSUE THREAD

**Issue by samoht** [realworldocaml/mdx#114]
This will help in the CI (as we require a very recent version of pandoc) and on windows.

**Comment by avsm** [comment]
see https://github.com/ocaml/omd/issues/175

@clecat, it's ok to use the trunk version of omd for this if it makes it easier; we can coordinate a release

**Comment by clecat** [comment]
You mean without the section feature ?
I'm not aware of the impact of this modification, it may have huge effects on the visual representation of the docs.
We will need to check it twice before doing any merge

**Comment by avsm** [comment]
I meant that the trunk version of omd is the one we will have to use in the long term, as it is a substantial rewrite and is much easier to maintain.  So testing and adding features to the trunk version is encouraged over the current release -- if we have to bug fix omd-dev to get this mdx feature done, then that's fine.

**Comment by clecat** [comment]
My work is going well for now, but I am not sure about the section id which was discussed in the omd issue:
When pandoc meets a header, it wraps it inside a section, and gives it an id derived from the content of the header. My question is about what we put inside this id:
 - pandoc uses [this](https://pandoc.org/MANUAL.html#extension-auto_identifiers) format, even using the specific tags if specified.
 - the other way to do is simply copying the html5 id format (an id must contain at least one character and may not contain any space characters), which is easier to do and not depandant of an apparently pandoc dependant decision. However, it will generate diffs in the already generated pages and it may broke some links (because we would ignore the tags)

I'm more attracted by the first solution, but it may not be relevant to reimplement this format, so I prefer to get another point of view

**Comment by clecat** [comment]
Additional information: Omd follows the CommonMark standard, which does not seems to have any behaviour of this kind for now (so no specs nor tests suite, see this [issue](https://talk.commonmark.org/t/anchors-in-markdown/247)), so this decision definitely has to be made in mdx.

**Comment by clecat** [comment]
Same idea with the (typography extension)[https://pandoc.org/MANUAL.html#typography].

**Comment by avsm** [comment]
Nice progress @clecat!  I think that following the pandoc algorithm for id resolution would be wise.  It covers quite a few corner cases, is reasonably predictable (e.g. editors might support it) and works for other input formats in the futur as well.  So if it's reasonably easy to reimplement, I'd vote for that direction rather than another scheme with HTML5 ids.

It might make sense to contribute this logic (and the typography ones) to omd as extensions, and then just simply use them here.  I can see us compiling omd to javascript as part of an OCaml documentation extension in the future, so centralising the Markdown logic in omd makes sense from that perspective.  Is your work using omd trunk for the moment?

**Comment by clecat** [comment]
Mmmmh okay I see, I will ask it on omd. And yes, I'm using the omd trunk (if by that you mean the unreleased version). I think I can try a pull request and see for the extensions afterwards.

This is the output of the tests:
```
-<section id="test0--toto--and-titi" class="level1">
+<section id="Test0, -toto- and titi" class="level1">
 <h1>Test0, -toto- and titi</h1>
 <p>toto</p>
 </section>
-<section id="test-toto-and-titi" class="level1">
-<h1>Test1, -toto- and titi!</h1>
+<section id="Test1, -toto- and titi! {#test-toto-and-titi}" class="level1">
+<h1>Test1, -toto- and titi! {#test-toto-and-titi}</h1>
 <p>titi</p>
 </section>
-<section id="test2-and-titi" class="level1">
+<section id="Test2, <toto> and titi!" class="level1">
 <h1>Test2, <toto> and titi!</h1>
 <p>yo!</p>
-<section id="test3-toto-and-titi" class="level2">
+<section id="Test3, <span class="toto">toto</a> and titi!" class="level2">
 <h2>Test3, <span class="toto">toto</a> and titi!</h2>
 <p>haha!!</p>
 </section>
 </section>
-<section id="test4-toto-a.nd.-io" class="level1">
-<h1>–Test4, ?toto! a.nd. I/O</h1>
+<section id="--Test4, ?toto! a.nd. I/O" class="level1">
+<h1>--Test4, ?toto! a.nd. I/O</h1>
 <p>foo</p>
 <div class="highlight">
 <pre><code class="language-ocaml">type &lt;record-name&gt; =
```
The only broken things are the ids mentioned earlier, the typograhy thing ("--") and some other work done by pandoc which is not part of the commonmark specs.

**Comment by clecat** [comment]
Long time no see, I did the needed work on omd, and I now have a code using it and passing our tests. However, as pandoc is a really huge project, we may expect some unexpected problems. A good thing to do would be to check with my version if some projects using mdx are not broken (e.g. rwo).

**Comment by samoht** [comment]
Do you have a branch of omd+mdx somewhere that I could try?

**Comment by clecat** [comment]
He is my mdx branch: https://github.com/clecat/mdx/tree/omd_pandoc.
For omd, just use the master branch: https://github.com/ocaml/omd

**Comment by samoht** [comment]
Can you open a PR?

**Comment by gpetiot** [comment]
I'm closing this one since the `output` command has been removed in #195
