### ISSUE TITLE
ocaml mdx failure on duniverse

### ISSUE THREAD

**Issue by mseri** [realworldocaml/mdx#175]
We are using `ocaml-mdx` for the new owl tutorials, but I cannot make it compile properly. The tests are failing with
```
   ocaml-mdx alias book/algodiff/runtest (exit 1)
(cd _build/default/book/algodiff && ../../../install/default/bin/ocaml-mdx test --prelude=prelude.ml --direction=to-md README.md)
Got an error while evaluating:
---
#require "core,core.top,ppx_jane,owl-top,owl-plplot";;

open Core
open Owl
open Bigarray

let () = Printexc.record_backtrace false
let () = 
  Owl_base_stats_prng.init 89;
  Owl_stats_prng.init 89
---
Line 2, characters 8-12:
Error: Unbound module Core
```
`core` seems to be correctly installed, also if I try to run them by hand they instead fail as
```
   opam exec -- ../../../install/default/bin/ocaml-mdx test --prelude=prelude.ml --direction=to-md README.md
ocaml-mdx-test: internal error, uncaught exception:
                Fl_package_base.No_such_package("unix", "")
```

I am not sure where to start to triage it.
The code is all here: https://github.com/mseri/owl_tutorials

**Comment by NathanReb** [comment]
Yeah the current released version of `mdx` doesn't work well with `duniverse`. In RWO we use a fork for now but we're working on getting it merged in `mdx`'s master. It takes some time because it was first based on a few hacks that we're trying to replace with more reliable solutions.

You can see #150 for that. Pinning mdx to this version should solve a few issues. In particular you have to invoke `ocaml-mdx rule --duniverse-mode` and it will do a couple things to make it work with a duniverse based project including adding explicit dependencies to packages in the duniverse for each `#require` statement and providing a dummy `findlib.conf` for the findlib dune port that had a few issues.

I'll try to rebase it today as we've made some progress on the findlib front and it's possible it currently is in an inconsistent state. RWO is using an older version of that fork atm.

**Comment by NathanReb** [comment]
Also note that it is normal that it doesn't work if you run it through `opam exec` as it relies on dune setting the `OCAMLPATH` for the duniverse's findlib!

**Comment by mseri** [comment]
Thanks! I was already using the duniverse fork, but with incorrect rules. I've updated them and promoted the changes, let's see if it works 🤞
