### ISSUE TITLE
More descriptive error messages for invalid `$MDX` comments

### ISSUE THREAD

**Issue by CraigFe** [realworldocaml/mdx#246]
My first attempt at using the `(* $MDX *)` syntax failed in an odd way:

```ocaml
(* $MDX part-begin=main*)
let x = ()
(* $MDX part-end *)
```

which gives the error message:

```text
Error in the OCaml file include code block in test.md at line 5:
In file ./test.ml, line 3: There is no part to end.
```

Turns out you need a space between the label and the comment terminator:

```diff
-(* $MDX part-begin=main*)
+(* $MDX part-begin=main *)
```

I think the unspaced form should probably be supported, but that isn't the main problem here. More generally, MDX will silently ignore comments with labels that it doesn't know about:

```ocaml
(* $MDX foo *)
```

I suggest emitting error messages along the lines of:
- "line n: could not parse `$MDX` comment"
- "line n: unrecognised label in `$MDX` comment: `foo`"

**Comment by gpetiot** [comment]
This syntax is only to delimit parts, other labels have to be listed in a `<!-- ... -->` comment and attached to a block. If the line does not match something like `(* $MDX part-begin=... *)` then it is just regular text.
To be able to catch that we would need a more generic `(* $MDX ... *)` syntax supported, and make the part delimiters a subset of that. Is it really worth it?

**Comment by CraigFe** [comment]
I think it's worth it to give good error messages in the case where the user was obviously trying and failing to do something MDX related. Particularly since MDX already has a separate label-passing system that users might try adding to `.ml` files in this way.

What if more features are supported in OCaml comments in future? Users will try to use these features with old versions of MDX and get no error message whatsoever.

I suspect it's not that much work to support a more generic syntax: it seems to be just a case of adding to the [regexes in `part.ml`](https://github.com/realworldocaml/mdx/blob/master/lib/part.ml#L63).

**Comment by NathanReb** [comment]
I think it would make sense to output a warning in such cases. The reason we went for a `(* $MDX ... *)` syntax is because we think it's unlikely have a regular comment mistaken for a part delimiter. I think it's equally unlikely that a regular comment starts with `$MDX` and that it would be okay to warn the user that MDX doesn't know how to parse it when that comes up.

Worst case scenario, it's just a warning so you can ignore it. I agree it's an annoying warning if it doesn't actually apply to you but we can think of something if it ever comes up.
